name: Build macOS Arm64 Binary

on:
  push:
    tags:
      - 'programminglanguage'

jobs:
  build-arm:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '17'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image from repo jar
        run: |
          native-image -jar elpl.jar elpl

      - name: Package into ZIP
        run: |
          zip ELPL-mac-arm64.zip elpl

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ELPL-mac-arm64.zip
          tag_name: programminglanguage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
